version: '3.5'

services:

  theoracle-front:
    image: node-docker:latest
    container_name: "theoracle-front"
    ports:
      - 80:5000
    volumes:
      - type: bind
        source: ../../data/dist
        target: /app

    environment:
     - BACK_URL=theoracle-back
        
    command: node theoracle-front/theoracle-front.js

    networks:
      - custom_network


    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  custom_network:
    external:
      name: custom_network
